apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: droidvirtvolumes.droidvirt.io
spec:
  group: droidvirt.io
  names:
    kind: DroidVirtVolume
    listKind: DroidVirtVolumeList
    plural: droidvirtvolumes
    singular: droidvirtvolume
    shortNames:
    - dvv
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
