apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: droidvirtvolumes.droidvirt.io
spec:
  group: droidvirt.io
  names:
    kind: DroidVirtVolume
    listKind: DroidVirtVolumeList
    plural: droidvirtvolumes
    singular: droidvirtvolume
    shortNames:
    - dvv
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Phone
    type: string
    JSONPath: .spec.device.phone
  - name: PVC
    type: string
    JSONPath: .status.relatedPVC
  - name: Phase
    type: string
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  versions:
  - name: v1alpha1
    served: true
    storage: true
