apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: droidvirts.droidvirt.io
spec:
  group: droidvirt.io
  names:
    kind: DroidVirt
    listKind: DroidVirtList
    plural: droidvirts
    singular: droidvirt
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
