apiVersion: apps/v1
kind: Deployment
metadata:
  name: droidvirt-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: droidvirt-ctrl
  template:
    metadata:
      labels:
        name: droidvirt-ctrl
    spec:
      serviceAccountName: droidvirt-ctrl
      containers:
        - name: droidvirt-ctrl
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - droidvirt-ctrl
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "droidvirt-ctrl"
