apiVersion: apps/v1
kind: Deployment
metadata:
  name: droidvirt-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: droidvirt-ctrl
  template:
    metadata:
      labels:
        name: droidvirt-ctrl
    spec:
      serviceAccountName: droidvirt-ctrl
      containers:
        - name: droidvirt-ctrl
          image: registry.cn-shanghai.aliyuncs.com/droidvirt/droidvirt-ctrl:202006031811
          command:
          - /usr/local/bin/droidvirt-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "droidvirt-ctrl"
