kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: droidvirt-ctrl
subjects:
- kind: ServiceAccount
  name: droidvirt-ctrl
roleRef:
  kind: Role
  name: droidvirt-ctrl
  apiGroup: rbac.authorization.k8s.io
