apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: droidvirt-ctrl
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  - virtualmachineinstances
  - virtualmachineinstancereplicasets
  - virtualmachineinstancepresets
  - virtualmachineinstancemigrations
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - droidvirt-ctrl
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - droidvirt.io
  resources:
  - '*'
  - droidvirt
  - droidvirtvolumes
  verbs:
  - '*'
